wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    python_version: 3.10.8
    start_time: 1672098206.777815
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 7
      - 23
      - 38
      - 39
      4: 3.10.8
      5: 0.13.7
      8:
      - 1
      - 5
